agents:
  queue: "default-{queue}"

# retry:
#   automatic:
#       limit: 3

label: "{name} ({slug})"
key: "build-{slug}"

commands:
  - echo \"+++ Start Services\"
  - bash scripts/tests/setup/start-services.sh
  - echo \"+++ Run Tests\"
  - bash scripts/cicd/10.test.sh
  - echo \"+++ Stop Services\"
  - bash scripts/tests/setup/stop-services.sh
  - echo \"+++ Run build\"
  - bash scripts/cicd/20.build.sh

plugins:
  - bureau14/qdb-artifacts#download-from-multiple-projects:
      download:
        clean: true
        projects:
          - project_id: "qdb-api-python"
            output-dir: "qdb"
            extract: true
            files:
              - "quasardb-*.whl"
            variant: linux-core2-release-py314
            git-ref: "refs/heads/sc-18913/buildkite-add-python-api-pipeline" # TODO remove hardcoded git-ref before merge
          - project_id: "quasardb"
            variant: linux-core2-release
            output-dir: "qdb"
            extract: true
            files:
              - "*-c-api.tar.zst!*"
              - "*-server.tar.zst!*"
              - "*-utils.tar.zst!*"
            git-ref: "refs/heads/sc-18547/buildkite" # TODO remove hardcoded git-ref before merge
      upload:
        files:
          - "dist/qdb_cloudwatch-*.whl"
      promote: {}
